'use client';

import { useEffect } from 'react';
import { ArrowLeft } from 'lucide-react';

export default function Terms() {
  useEffect(() => {
    document.title = 'Terms of Service | eiwi';
  }, []);

  return (
    <div className="min-h-screen text-white" style={{ background: '#0b0b14' }}>
      <nav className="border-b border-white/[0.07] bg-black/70 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-screen-xl mx-auto px-6 py-4 flex items-center gap-4">
          <a href="/" className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-gradient-to-br from-violet-500 to-fuchsia-600 rounded-xl flex items-center justify-center">
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M2 7L6 11L12 3" stroke="white" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
            <span className="text-xl font-semibold tracking-tight">eiwi</span>
          </a>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <a href="/" className="flex items-center gap-2 text-zinc-500 hover:text-zinc-300 transition-colors text-sm mb-10">
          <ArrowLeft className="w-4 h-4" />
          Back
        </a>

        <h1 className="text-4xl font-bold tracking-tight text-white mb-2">Terms of Service</h1>
        <p className="text-zinc-500 text-sm mb-12">Last updated: May 15, 2026</p>

        <div className="space-y-10 text-zinc-400 text-sm leading-relaxed">

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">1. Agreement to Terms</h2>
            <p>By accessing or using eiwi ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. The Service is operated by Nick Spridgeon ("we", "us", or "our").</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">2. Description of Service</h2>
            <p>eiwi is an AI-powered code analysis platform that connects to your GitHub repositories and provides automated code reviews, security analysis, and technical assessments. Analysis results are generated by artificial intelligence and are provided for informational purposes only.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">3. GitHub Authorization</h2>
            <p>To use eiwi, you must authorize access to your GitHub account. By doing so, you grant us permission to read your repository contents for the purpose of performing code analysis. We will never modify, delete, or write to your repositories. You can revoke this access at any time through your GitHub account settings.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">4. AI-Generated Analysis</h2>
            <p>Analysis results provided by eiwi are generated by third-party AI models, including OpenAI. These results:</p>
            <ul className="list-disc list-inside mt-3 space-y-2 ml-2">
              <li>Are not guaranteed to be accurate, complete, or error-free</li>
              <li>Should not be relied upon as the sole basis for security or architectural decisions</li>
              <li>May contain false positives or miss genuine issues</li>
              <li>Do not constitute professional security, legal, or engineering advice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside mt-3 space-y-2 ml-2">
              <li>Analyze repositories you do not own or have explicit permission to analyze</li>
              <li>Attempt to reverse engineer, circumvent, or exploit the Service</li>
              <li>Use the Service for any unlawful purpose</li>
              <li>Resell or redistribute analysis results as your own product without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">6. Usage Limits</h2>
            <p>Free accounts are limited to 10 repository analyses per day. We reserve the right to modify these limits at any time. Exceeding usage limits may result in temporary suspension of your account.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">7. Intellectual Property</h2>
            <p>Your code and repositories remain your property at all times. We claim no ownership over any code or content you submit for analysis. The eiwi platform, including its design, features, and branding, is owned by us and protected by applicable intellectual property laws.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">8. Disclaimer of Warranties</h2>
            <p>The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or completely secure. You use the Service at your own risk.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to any security vulnerabilities that were not detected or were incorrectly assessed by our AI analysis.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">10. Termination</h2>
            <p>We reserve the right to suspend or terminate your access to the Service at any time, for any reason, with or without notice. You may also delete your account at any time by contacting us.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">11. Changes to Terms</h2>
            <p>We may update these Terms of Service from time to time. We will notify users of significant changes by updating the date at the top of this page. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">12. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of the United States. Any disputes arising from these Terms or your use of the Service shall be resolved in the appropriate courts of the United States.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">13. Contact</h2>
            <p>If you have any questions about these Terms, please contact us at <span className="text-violet-400">support@eiwi.app</span>.</p>
          </section>

        </div>
      </div>
    </div>
  );
}